export const cartActions = {
    CLEAR_SHOPPING_CART: 'CLEAR_SHOPPING_CART',
    CHANGE_QTY: 'CHANGE_QTY',
    REMOVE_ITEM: 'REMOVE_ITEM',
    ADD_ONE: 'ADD_ONE',
    REMOVE_ONE: 'REMOVE_ONE',
    SAVE_QTY: 'SAVE_QTY',
    CANCEL_CHANGE_QTY: 'CANCEL_CHANGE_QTY',
    LOAD_ITEMS: 'LOAD_ITEMS'
};
